# -*- coding: utf-8 -*-
"""SL+Decision_Tree_Algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uAOt_YYxdSl-rRjlBTePQndWzMIkvmN3

#Name:P.Rafeeq
#ROll No:21X05A6740
#BRanch: CSE(DS)

#Project Title: Prediction of IRIS.csv dataset for Decision Tree algorithm using supervised lesrning machine algorithm

#Problem Statement : A American based Botanical gardens grow iris flower in their labs but using Bio technology in single tree different type of variety is grow.
#As a data science engineer find out how much accurany their all categerioes contained same species.

#Conclusion: According to my decision accurany would be 1%
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Decision Tree classifier
decision_tree = DecisionTreeClassifier()

# Train the classifier on the training data
decision_tree.fit(X_train, y_train)

# Make predictions on the test data
y_pred = decision_tree.predict(X_test)



# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

